### ISSUE TITLE
Question ：Failed ALPN negotiation: Unable to find compatible protocol

### ISSUE THREAD

**Issue by TO-21** [apache/rocketmq-clients#281]
I need some help，
I tried to connect to my local RocketMQ service, but this exception left me confused

Here's my code ，thanks
``` java
    public static void main(String[] args){
        ClientServiceProvider provider = ClientServiceProvider.loadService();

        ClientConfiguration configuration = ClientConfiguration.newBuilder()
                .setRequestTimeout(Duration.ofSeconds(10))
                .setEndpoints("172.18.98.74:9876")
                .build();
        try {
            Producer producer = provider.newProducerBuilder()
                    .setClientConfiguration(configuration)
                    .build();

            Message message = provider.newMessageBuilder()
                    .setTopic("TOPIC_TEST")
                    .setBody("HelloWorld".getBytes())
                    .build();

            producer.send(message);
        } catch (ClientException e) {
            e.printStackTrace();
        }
    }
```
Console message
```
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: Failed ALPN negotiation: Unable to find compatible protocol
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:544)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by aaron-ai** [comment]
Have you started rocketmq proxy?

**Comment by TO-21** [comment]
> Have you started rocketmq proxy?

Thank you for your reminder. I checked the proxy service, opened the port, and changed the connection address to the proxy service port. Now the problem is solved.
