### ISSUE TITLE
php sdk 是不是不能用，demo报错 failed to connect to all addresses

### ISSUE THREAD

**Issue by kunlun2015** [apache/rocketmq-clients#317]
给出的demo producer的时候报 failed to connect to all addresses

mq 服务报错如下：
2022-12-19 10:58:00 INFO NettyServerCodecThread_2 - NETTY SERVER PIPELINE: channelInactive, the channel[192.168.30.250:53000]
2022-12-19 10:58:00 INFO NettyServerCodecThread_2 - NETTY SERVER PIPELINE: channelUnregistered, the channel[192.168.30.250:53000]
2022-12-19 10:58:21 INFO NettyServerCodecThread_4 - NETTY SERVER PIPELINE: channelRegistered 192.168.30.250:53009
2022-12-19 10:58:21 INFO NettyServerCodecThread_4 - NETTY SERVER PIPELINE: channelActive, the channel[192.168.30.250:53009]
2022-12-19 10:58:22 ERROR NettyServerCodecThread_4 - decode exception, 192.168.30.250:53009
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 16777216: 1347569956 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:503) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:489) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:376) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:419) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at org.apache.rocketmq.remoting.netty.NettyDecoder.decode(NettyDecoder.java:43) ~[rocketmq-remoting-4.9.3-sohu.jar:4.9.3-sohu]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:332) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at org.apache.rocketmq.remoting.netty.NettyRemotingServer$HandshakeHandler.channelRead0(NettyRemotingServer.java:451) [rocketmq-remoting-4.9.3-sohu.jar:4.9.3-sohu]
        at org.apache.rocketmq.remoting.netty.NettyRemotingServer$HandshakeHandler.channelRead0(NettyRemotingServer.java:392) [rocketmq-remoting-4.9.3-sohu.jar:4.9.3-sohu]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]
2022-12-19 10:58:22 INFO NettyServerNIOSelector_3_3 - closeChannel: close the connection to remote address[192.168.30.250:53009] result: true

**Comment by aaron-ai** [comment]
Yes. PHP SDK is still work-in-progress.

**Comment by phoema** [comment]
php sdk可以用了吗？
