### ISSUE TITLE
Java: Example failed on macOS 10.13.6

### ISSUE THREAD

**Issue by bibable** [apache/rocketmq-clients#354]
Following is the full exception. I think the key lies in

> java.lang.UnsatisfiedLinkError: /private/var/folders/z8/xnq7y9ns7nzgznt3yvmwzhbm0000gn/T/liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib: dlopen(/private/var/folders/z8/xnq7y9ns7nzgznt3yvmwzhbm0000gn/T/liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib, 1): no suitable image found.  Did find:
	/private/var/folders/z8/xnq7y9ns7nzgznt3yvmwzhbm0000gn/T/liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib: cannot load 'liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib' (load command 0x80000034 is unknown)

I googled 'load command 0x80000034 is unknown' and it seemed a problem with newer the native lib file and the older macOS version.

Full log:
`java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_osx_x86_64, netty_tcnative_x86_64, netty_tcnative]
	at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:107)
	at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:705)
	at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:146)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:230)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at org.apache.rocketmq.client.java.rpc.RpcClientImpl.<init>(RpcClientImpl.java:82)
	at org.apache.rocketmq.client.java.impl.ClientManagerImpl.getRpcClient(ClientManagerImpl.java:177)
	at org.apache.rocketmq.client.java.impl.ClientManagerImpl.queryRoute(ClientManagerImpl.java:193)
	at org.apache.rocketmq.client.java.impl.ClientImpl.fetchTopicRoute0(ClientImpl.java:635)
	at org.apache.rocketmq.client.java.impl.ClientImpl.fetchTopicRoute(ClientImpl.java:611)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.rocketmq.client.java.impl.ClientImpl.startUp(ClientImpl.java:192)
	at org.apache.rocketmq.client.java.impl.producer.ProducerImpl.startUp(ProducerImpl.java:113)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.Callables.lambda$threadRenaming$3(Callables.java:103)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.UnsatisfiedLinkError: /private/var/folders/z8/xnq7y9ns7nzgznt3yvmwzhbm0000gn/T/liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib: dlopen(/private/var/folders/z8/xnq7y9ns7nzgznt3yvmwzhbm0000gn/T/liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib, 1): no suitable image found.  Did find:
	/private/var/folders/z8/xnq7y9ns7nzgznt3yvmwzhbm0000gn/T/liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib: cannot load 'liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib' (load command 0x80000034 is unknown)
	/private/var/folders/z8/xnq7y9ns7nzgznt3yvmwzhbm0000gn/T/liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib: stat() failed with errno=20
		at java.lang.ClassLoader$NativeLibrary.load(Native Method)
		at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
		at java.lang.Runtime.load0(Runtime.java:809)
		at java.lang.System.load(System.java:1086)
		at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
		at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:319)
		at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:196)
		at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:98)
		... 22 more
		Suppressed: java.lang.UnsatisfiedLinkError: /private/var/folders/z8/xnq7y9ns7nzgznt3yvmwzhbm0000gn/T/liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib: dlopen(/private/var/folders/z8/xnq7y9ns7nzgznt3yvmwzhbm0000gn/T/liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib, 1): no suitable image found.  Did find:
	/private/var/folders/z8/xnq7y9ns7nzgznt3yvmwzhbm0000gn/T/liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib: cannot load 'liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib' (load command 0x80000034 is unknown) 
	/private/var/folders/z8/xnq7y9ns7nzgznt3yvmwzhbm0000gn/T/liborg_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_645940359330076104701.dylib: stat() failed with errno=20
			at java.lang.ClassLoader$NativeLibrary.load(Native Method)
			at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
			at java.lang.Runtime.load0(Runtime.java:809)
			at java.lang.System.load(System.java:1086)
			at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:353)
			at java.security.AccessController.doPrivileged(Native Method)
			at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:345)
			at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:311)
			... 24 more`

**Comment by lizhanhui** [comment]
The tcnative shared library, embedded in netty, is not compatible with your OS. macOS frequently fails at backward compatibility.

One way to walk around is to try a newer version of netty. 

BTW, is your macOS ARM-based? It would be helpful to verify if netty has CPU arch in consideration and is loading the correct shared library.

**Comment by bibable** [comment]
It's Intel-based.
