### ISSUE TITLE
新版本sdk如何设置重试策略？

### ISSUE THREAD

**Issue by orchidFang** [apache/rocketmq-clients#413]
请问PushConsumer如何主动设置失败情况下的重试策略呢？

**Comment by aaron-ai** [comment]
新版本 SDK 中，我们认为重试策略应该是由 Group 来定义而并非是每个客户端自己去定义的。
cc @drpmma

**Comment by orchidFang** [comment]
> 新版本 SDK 中，我们认为重试策略应该是由 Group 来定义而并非是每个客户端自己去定义的。你可以使用 sh mqadmin updateSubGroup 命令来进行配置。 cc @drpmma

谢谢，知道了。

**Comment by orchidFang** [comment]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/6478487/226368256-4cf5cc30-0ced-4b91-bd8e-c77349798e3f.png">
你好，为什么使用updateSubGroup时，经检查重试策略的json配置没有问题，会报json解析错误。

**Comment by orchidFang** [comment]
你好，使用updateSubGroup设置重试策略时，经检查json配置没有问题，但报json解析错误。

cc @aaron-ai 

COMMAND:

./mqadmin updateSubGroup -n localhost:9876 -g system -p {"type":"EXPONENTIAL","exponentialRetryPolicy":{"initial":5000,"max":7200000,"multiplier":2}}

ERROR MSG:

org.apache.rocketmq.tools.command.SubCommandException: UpdateSubGroupSubCommand command failed
at org.apache.rocketmq.tools.command.consumer.UpdateSubGroupSubCommand.execute(UpdateSubGroupSubCommand.java:211)
at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:160)
at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:110)
Caused by: com.alibaba.fastjson.JSONException: error parse true
at com.alibaba.fastjson.parser.JSONLexerBase.scanTrue(JSONLexerBase.java:4642)
at com.alibaba.fastjson.parser.JSONLexerBase.nextToken(JSONLexerBase.java:148)
at com.alibaba.fastjson.parser.DefaultJSONParser.(DefaultJSONParser.java:170)
at com.alibaba.fastjson.parser.DefaultJSONParser.(DefaultJSONParser.java:141)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:378)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:298)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:588)
at org.apache.rocketmq.tools.command.consumer.UpdateSubGroupSubCommand.execute(UpdateSubGroupSubCommand.java:159)
... 2 more
