### ISSUE TITLE
CPP client: pure virtual method called

### ISSUE THREAD

**Issue by mikehb** [apache/rocketmq-clients#414]
This is the backtrace below from the master branch,
```
#0  0x00007f8ccfaafe5c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007f8ccfa5fa76 in raise () from /lib64/libc.so.6
#2  0x00007f8ccfa49886 in abort () from /lib64/libc.so.6
#3  0x00007f8ccfca2b97 in __gnu_cxx::__verbose_terminate_handler() [clone .cold] () from /lib64/libstdc++.so.6
#4  0x00007f8ccfcae48c in __cxxabiv1::__terminate(void (*)()) () from /lib64/libstdc++.so.6
#5  0x00007f8ccfcae4f7 in std::terminate() () from /lib64/libstdc++.so.6
#6  0x00007f8ccfcaf225 in __cxa_pure_virtual () from /lib64/libstdc++.so.6
#7  0x0000000001f870f1 in grpc::ClientBidiReactor<apache::rocketmq::v2::TelemetryCommand, apache::rocketmq::v2::TelemetryCommand>::StartWrite(apache::rocketmq::v2::TelemetryCommand const*, grpc::WriteOptions) ()
#8  0x0000000001f8607d in grpc::ClientBidiReactor<apache::rocketmq::v2::TelemetryCommand, apache::rocketmq::v2::TelemetryCommand>::StartWrite(apache::rocketmq::v2::TelemetryCommand const*) ()
#9  0x0000000001f8405c in rocketmq::TelemetryBidiReactor::fireWrite() ()
#10 0x0000000001f83c45 in rocketmq::TelemetryBidiReactor::write(apache::rocketmq::v2::TelemetryCommand) ()
#11 0x0000000001f7e612 in rocketmq::SessionImpl::syncSettings() ()
#12 0x0000000001ea5770 in rocketmq::ClientImpl::syncClientSettings() ()
#13 0x0000000001ea31ef in rocketmq::ClientImpl::start()::{lambda()#3}::operator()() const ()
#14 0x0000000001ea9f36 in void std::__invoke_impl<void, rocketmq::ClientImpl::start()::{lambda()#3}&>(std::__invoke_other, rocketmq::ClientImpl::start()::{lambda()#3}&) ()
#15 0x0000000001ea92f8 in std::enable_if<std::__and_<std::is_void<void>, std::__is_invocable<rocketmq::ClientImpl::start()::{lambda()#3}&> >::value, void>::type std::__invoke_r<void, rocketmq::ClientImpl::start()::{lambda()#3}&>(rocketmq::ClientImpl::start()::{lambda()#3}&) ()
#16 0x0000000001ea89f2 in std::_Function_handler<void (), rocketmq::ClientImpl::start()::{lambda()#3}>::_M_invoke(std::_Any_data const&) ()
#17 0x0000000001b8cf08 in std::function<void ()>::operator()() const (this=0x44a8098) at /usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:591
#18 0x0000000001f8f447 in rocketmq::SchedulerImpl::execute(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>) ()
#19 0x0000000001fa5074 in void std::__invoke_impl<void, void (*&)(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>), std::error_code const&, std::weak_ptr<rocketmq::TimerTask>&>(std::__invoke_other, void (*&)(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>), std::error_code const&, std::weak_ptr<rocketmq::TimerTask>&) ()
#20 0x0000000001fa49fb in std::__invoke_result<void (*&)(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>), std::error_code const&, std::weak_ptr<rocketmq::TimerTask>&>::type std::__invoke<void (*&)(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>), std::error_code const&, std::weak_ptr<rocketmq::TimerTask>&>(void (*&)(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>), std::error_code const&, std::weak_ptr<rocketmq::TimerTask>&) ()
#21 0x0000000001fa3feb in void std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>::__call<void, std::error_code const&, 0ul, 1ul>(std::tuple<std::error_code const&>&&, std::_Index_tuple<0ul, 1ul>)
    ()
#22 0x0000000001fa3215 in void std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>::operator()<std::error_code const&, void>(std::error_code const&) ()
#23 0x0000000001fa1bb9 in asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code>::operator()() ()
#24 0x0000000001fa0592 in void asio::asio_handler_invoke<asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code> >(asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code>&, ...) ()
#25 0x0000000001f9f6cc in void asio_handler_invoke_helpers::invoke<asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code>, std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)> >(asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code>&, std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>&) ()
#26 0x0000000001f9e846 in void asio::detail::handler_work<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, asio::any_io_executor, void>::complete<asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code> >(asio::detail::binder1<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, std::error_code>&, std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>&) ()
#27 0x0000000001f9cf66 in asio::detail::wait_handler<std::_Bind<void (*(std::_Placeholder<1>, std::weak_ptr<rocketmq::TimerTask>))(std::error_code const&, std::weak_ptr<rocketmq::TimerTask>)>, asio::any_io_executor>::do_complete(void*, asio::detail::scheduler_operation*, std::error_code const&, unsigned long) ()
#28 0x0000000001f90a5e in asio::detail::scheduler_operation::complete(void*, std::error_code const&, unsigned long) ()
#29 0x0000000001f93b3d in asio::detail::scheduler::do_run_one(asio::detail::conditionally_enabled_mutex::scoped_lock&, asio::detail::scheduler_thread_info&, std::error_code const&) ()
#30 0x0000000001f93648 in asio::detail::scheduler::run(std::error_code&) ()
#31 0x0000000001f93ee5 in asio::io_context::run(std::error_code&) ()
#32 0x0000000001f8e7fe in rocketmq::SchedulerImpl::start()::{lambda()#1}::operator()() const ()
#33 0x0000000001f8fe90 in void std::__invoke_impl<void, rocketmq::SchedulerImpl::start()::{lambda()#1}>(std::__invoke_other, rocketmq::SchedulerImpl::start()::{lambda()#1}&&) ()
#34 0x0000000001f8fe53 in std::__invoke_result<rocketmq::SchedulerImpl::start()::{lambda()#1}>::type std::__invoke<rocketmq::SchedulerImpl::start()::{lambda()#1}>(rocketmq::SchedulerImpl::start()::{lambda()#1}&&) ()
#35 0x0000000001f8fe00 in void std::thread::_Invoker<std::tuple<rocketmq::SchedulerImpl::start()::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) ()
#36 0x0000000001f8fdd4 in std::thread::_Invoker<std::tuple<rocketmq::SchedulerImpl::start()::{lambda()#1}> >::operator()() ()
#37 0x0000000001f8fdb8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<rocketmq::SchedulerImpl::start()::{lambda()#1}> > >::_M_run() ()
#38 0x00007f8ccfcdbc03 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#39 0x00007f8ccfaae12d in start_thread () from /lib64/libc.so.6
#40 0x00007f8ccfb2fbc0 in clone3 () from /lib64/libc.so.6
```

**Comment by mikehb** [comment]
This could be reproduced when rocketmq server is either not started or network broken

**Comment by lizhanhui** [comment]
It's an upstream gRPC issue.

**Comment by flyish** [comment]
@lizhanhui  Is it the grpc version? Which version should I use?
