### ISSUE TITLE
grpc-js Call cancelled 

### ISSUE THREAD

**Issue by eric-projects** [apache/rocketmq-clients#653]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Programming Language of the Client

Node.js

### Runtime Platform Environment

ubuntu20.04.5

### RocketMQ Version of the Client/Server

5.0

### Run or Compiler Version

nodejs 18.17.0，18.0.0，16.19.0

### Describe the Bug

Producer [class Producer extends BaseClient]
Error: 1 CANCELLED: Call cancelled
    at callErrorFromStatus (/root/rocketmq-clients/nodejs/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/root/rocketmq-clients/nodejs/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/root/rocketmq-clients/nodejs/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/root/rocketmq-clients/nodejs/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /root/rocketmq-clients/nodejs/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/root/rocketmq-clients/nodejs/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.queryRoute (/root/rocketmq-clients/nodejs/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /root/rocketmq-clients/nodejs/dist/client/RpcClient.js:62:20
    at new Promise (<anonymous>)
    at RpcClient.queryRoute (/root/rocketmq-clients/nodejs/dist/client/RpcClient.js:61:16)
    at RpcClientManager.queryRoute (/root/rocketmq-clients/nodejs/dist/client/RpcClientManager.js:66:32)
    at #fetchTopicRoute (/root/rocketmq-clients/nodejs/dist/client/BaseClient.js:178:54)
    at Producer.getRouteData (/root/rocketmq-clients/nodejs/dist/client/BaseClient.js:170:57)
    at #getPublishingLoadBalancer (/root/rocketmq-clients/nodejs/dist/producer/Producer.js:216:47)
    at #send (/root/rocketmq-clients/nodejs/dist/producer/Producer.js:142:67) {
  code: 1,
  details: 'Call cancelled',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

### Steps to Reproduce

1、pull rocketmq-clients code
2、pull proto code
3、 cd rocketmq-clients/nodejs
4、 npm install
5、 npm run init
6、 npm run build
7、 use dist folder run Producer test

### What Did You Expect to See?

message send success

### What Did You See Instead?

run error :Error: 1 CANCELLED: Call cancelled

**Comment by eric-projects** [comment]
![image](https://github.com/apache/rocketmq-clients/assets/31500407/12388797-8096-448d-acd7-8ef15e98c5e8)
![image](https://github.com/apache/rocketmq-clients/assets/31500407/711c3bed-65b6-44c3-8cad-e045233cda48)

**Comment by moling1234** [comment]
The same problem occurs on my client but I can't solve it, I want help!

**Comment by moling1234** [comment]
There is also the nodejs client that will be disconnected, which is a serious problem. @ShadowySpirits

**Comment by TimZhao-SH** [comment]
I tracked namesrv. log and found the following error

![node-rocketmq-error](https://github.com/apache/rocketmq-clients/assets/153474412/43fb0859-3ae0-4c98-9541-0dbbc0f9763f)

**Comment by easyfrog** [comment]
same question! how to resole this??

```bash
[class SimpleConsumer extends Consumer]
runGroupIndex ERROR: Error: Startup the rocketmq client failed, clientId=d1c7d477527b@29@14@lubgqg2n, error=Error: 1 CANCELLED: Call cancelled
    at SimpleConsumer.startup (/usr/rest-server/node_modules/rocketmq-client-nodejs/dist/client/BaseClient.js:83:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (eval at getApiHandlerFuncObject (/usr/rest-server/src/utils/utils.js:101:21), <anonymous>:194:9)
    at async eval (eval at getApiHandlerFuncObject (/usr/rest-server/src/utils/utils.js:101:21), <anonymous>:208:5)
    at async runGroupIndex (/usr/rest-server/src/routes/index.js:95:13) {
  cause: Error: 1 CANCELLED: Call cancelled
      at callErrorFromStatus (/usr/rest-server/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
      at Object.onReceiveStatus (/usr/rest-server/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
      at Object.onReceiveStatus (/usr/rest-server/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
      at Object.onReceiveStatus (/usr/rest-server/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
      at /usr/rest-server/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
  for call at
      at ServiceClientImpl.makeUnaryRequest (/usr/rest-server/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
      at ServiceClientImpl.queryRoute (/usr/rest-server/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
      at /usr/rest-server/node_modules/rocketmq-client-nodejs/dist/client/RpcClient.js:54:20
      at new Promise (<anonymous>)
      at RpcClient.queryRoute (/usr/rest-server/node_modules/rocketmq-client-nodejs/dist/client/RpcClient.js:53:16)
      at RpcClientManager.queryRoute (/usr/rest-server/node_modules/rocketmq-client-nodejs/dist/client/RpcClientManager.js:66:32)
      at #fetchTopicRoute (/usr/rest-server/node_modules/rocketmq-client-nodejs/dist/client/BaseClient.js:178:54)
      at SimpleConsumer.updateRoutes (/usr/rest-server/node_modules/rocketmq-client-nodejs/dist/client/BaseClient.js:163:40)
      at #startup (/usr/rest-server/node_modules/rocketmq-client-nodejs/dist/client/BaseClient.js:92:20)
      at SimpleConsumer.startup (/usr/rest-server/node_modules/rocketmq-client-nodejs/dist/client/BaseClient.js:80:32) {
    code: 1,
    details: 'Call cancelled',
    metadata: Metadata { internalRepr: Map(0) {}, options: {} }
  }
}

```

**Comment by JanYork** [comment]
I have this problem too? Is this a bug? How to solve?

**Comment by eric-projects** [comment]
已经解决，需要升级rocketmq服务器端版本到5.x,并开启 rocketmq  proxy

详细内容可查看 此issues https://github.com/apache/rocketmq-clients/issues/721
@JanYork @moling1234
