### ISSUE TITLE
Error: 1 CANCELLED: Call cancelled from nodejs-client

### ISSUE THREAD

**Issue by Luwei199169** [apache/rocketmq-clients#721]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Programming Language of the Client

Node.js

### Runtime Platform Environment

windows 10+docker

### RocketMQ Version of the Client/Server

rocketmq-client-nodejs 1.0.0

### Run or Compiler Version

Node.js v18.19.1 

### Describe the Bug

Begin to startup the rocketmq client, clientId=DESKTOP-4MD3G42@14964@0@luqgts4n
Startup the rocketmq client successfully, clientId=DESKTOP-4MD3G42@14964@0@luqgts4n
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: 1 CANCELLED: Call cancelled
    at callErrorFromStatus (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\call.js:31:19)
    at Object.onReceiveStatus (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\client.js:193:76)
    at Object.onReceiveStatus (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:360:141)
    at Object.onReceiveStatus (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:323:181)
    at C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\resolving-call.js:129:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\client.js:161:32)
    at ServiceClientImpl.queryRoute (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\make-client.js:105:19)
    at C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\client\RpcClient.js:54:20
    at new Promise (<anonymous>)
    at RpcClient.queryRoute (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\client\RpcClient.js:53:16)
    at RpcClientManager.queryRoute (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\client\RpcClientManager.js:66:32)
    at #fetchTopicRoute (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\client\BaseClient.js:178:54)
    at Producer.getRouteData (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\client\BaseClient.js:170:57)
    at #getPublishingLoadBalancer (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\producer\Producer.js:216:47)
    at #send (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\producer\Producer.js:142:67) {
  code: 1,
  details: 'Call cancelled',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

Node.js v18.19.1

### Steps to Reproduce

https://github.com/apache/rocketmq-clients/tree/master/nodejs/examples运行此示例出现，

### What Did You Expect to See?

docker正确部署mqnamesrv，mqbroker下，如何解决此问题

### What Did You See Instead?

docker正确部署mqnamesrv，mqbroker下，如何解决此问题

### Additional Context

Begin to startup the rocketmq client, clientId=DESKTOP-4MD3G42@14964@0@luqgts4n
Startup the rocketmq client successfully, clientId=DESKTOP-4MD3G42@14964@0@luqgts4n
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: 1 CANCELLED: Call cancelled
    at callErrorFromStatus (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\call.js:31:19)
    at Object.onReceiveStatus (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\client.js:193:76)
    at Object.onReceiveStatus (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:360:141)
    at Object.onReceiveStatus (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:323:181)
    at C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\resolving-call.js:129:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\client.js:161:32)
    at ServiceClientImpl.queryRoute (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\@grpc\grpc-js\build\src\make-client.js:105:19)
    at C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\client\RpcClient.js:54:20
    at new Promise (<anonymous>)
    at RpcClient.queryRoute (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\client\RpcClient.js:53:16)
    at RpcClientManager.queryRoute (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\client\RpcClientManager.js:66:32)
    at #fetchTopicRoute (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\client\BaseClient.js:178:54)
    at Producer.getRouteData (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\client\BaseClient.js:170:57)
    at #getPublishingLoadBalancer (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\producer\Producer.js:216:47)
    at #send (C:\Users\mib\Desktop\nest-project\rocket-mq\node_modules\rocketmq-client-nodejs\dist\producer\Producer.js:142:67) {
  code: 1,
  details: 'Call cancelled',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

**Comment by drpmma** [comment]
@fengmk2 

please have a look

**Comment by fengmk2** [comment]
重现方式能否提供一下？

**Comment by JanYork** [comment]
> 重新方式能否提供一下？

https://github.com/apache/rocketmq-clients/tree/master/nodejs/examples 官方这个示例运行就会报错：details: 'Call cancelled'

**Comment by eric-projects** [comment]
> 重现方式能否提供一下？

使用系统：ubuntu20
nodejs版本：18.17.0
1、访问npm包：https://www.npmjs.com/package/rocketmq-client-nodejs
2、空文件夹 npm init 
3、npm install rocketmq-client-nodejs
4、创建index.js  放入npm包示例 Producer
5、node index.js 
得到异常：
Begin to startup the rocketmq client, clientId=ubuntu@593473@0@lwpq8nq1
Startup the rocketmq client successfully, clientId=ubuntu@593473@0@lwpq8nq1
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: 1 CANCELLED: Call cancelled

**Comment by eric-projects** [comment]
> 重现方式能否提供一下？
“Error: 1 CANCELLED: Call cancelled”
这个异常我看好多人都遇到了。难道你们当时能跑通吗，如果能是不是环境配置没有完全公布于众。

**Comment by JanYork** [comment]
你是否启用了rocketmq-proxy？

**Comment by eric-projects** [comment]
> 你是否启用了rocketmq-proxy？

不清楚，rocketmq-proxy是什么，怎么看是否启用，以及怎么取消。
@JanYork

**Comment by JanYork** [comment]
> > 你是否启用了rocketmq-proxy？
> 
> 不清楚，rocketmq-proxy是什么，怎么看是否启用，以及怎么取消。
> @JanYork 

如果你使用新版本的rocketmq-client，也就是grpc版本的客户端，那么需要开启rocketmq-proxy才可以成功连接，端口也不在是直连nameserve，而是连接proxy的端口，你可以看看官方文档

**Comment by eric-projects** [comment]
> > > 你是否启用了rocketmq-proxy？
> > 
> > 
> > 不清楚，rocketmq-proxy是什么，怎么看是否启用，以及怎么取消。
> > @JanYork
> 
> 如果你使用新版本的rocketmq-client，也就是grpc版本的客户端，那么需要开启rocketmq-proxy才可以成功连接，端口也不在是直连nameserve，而是连接proxy的端口，你可以看看官方文档

好的，谢谢。我们现在用的是4.x的。等升级版本启用proxy后再看看。

**Comment by JanYork** [comment]
> > > > 你是否启用了rocketmq-proxy？
> > > 
> > > 
> > > 不清楚，rocketmq-proxy是什么，怎么看是否启用，以及怎么取消。
> > > @JanYork
> > 
> > 如果你使用新版本的rocketmq-client，也就是grpc版本的客户端，那么需要开启rocketmq-proxy才可以成功连接，端口也不在是直连nameserve，而是连接proxy的端口，你可以看看官方文档
> 
> 好的，谢谢。我们现在用的是4.x的。等升级版本启用proxy后再看看。

这个仓库是5.x版本client的仓库，之前4.x版本的node client不在这个仓库。

**Comment by eric-projects** [comment]
> > > > > 你是否启用了rocketmq-proxy？
> > > > 
> > > > 
> > > > 不清楚，rocketmq-proxy是什么，怎么看是否启用，以及怎么取消。
> > > > @JanYork
> > > 
> > > 
> > > 如果你使用新版本的rocketmq-client，也就是grpc版本的客户端，那么需要开启rocketmq-proxy才可以成功连接，端口也不在是直连nameserve，而是连接proxy的端口，你可以看看官方文档
> > 
> > 
> > 好的，谢谢。我们现在用的是4.x的。等升级版本启用proxy后再看看。
> 
> 这个仓库是5.x版本client的仓库，之前4.x版本的node client不在这个仓库。

好的，再次感谢。

**Comment by JanYork** [comment]
> > > > 你是否启用了rocketmq-proxy？
> > > 
> > > 
> > > 不清楚，rocketmq-proxy是什么，怎么看是否启用，以及怎么取消。
> > > @JanYork
> > 
> > 如果你使用新版本的rocketmq-client，也就是grpc版本的客户端，那么需要开启rocketmq-proxy才可以成功连接，端口也不在是直连nameserve，而是连接proxy的端口，你可以看看官方文档
> 
> 好的，谢谢。我们现在用的是4.x的。等升级版本启用proxy后再看看。

4.x版本只能支持remoting协议，之前4.x node版本的client是基于之前的cpp版本的，而且处于dev状态，如果你要在node中使用rocketmq，我建议升级5.x。

**Comment by eric-projects** [comment]
> > > > > 你是否启用了rocketmq-proxy？
> > > > 
> > > > 
> > > > 不清楚，rocketmq-proxy是什么，怎么看是否启用，以及怎么取消。
> > > > @JanYork
> > > 
> > > 
> > > 如果你使用新版本的rocketmq-client，也就是grpc版本的客户端，那么需要开启rocketmq-proxy才可以成功连接，端口也不在是直连nameserve，而是连接proxy的端口，你可以看看官方文档
> > 
> > 
> > 好的，谢谢。我们现在用的是4.x的。等升级版本启用proxy后再看看。
> 
> 4.x版本只能支持remoting协议，之前4.x node版本的client是基于之前的cpp版本的，而且处于dev状态，如果你要在node中使用rocketmq，我建议升级5.x。

已经升级5.x，测试通过了。非常感谢

**Comment by Gufang666** [comment]
> 现在新版本的nodejs，哥们有没有测试过消息发送速率，我测试700条每秒，发送效率不如之间cpp版本的nodejs-client

现在新版本的nodejs，哥们有没有测试过消息发送速率，我测试700条每秒，发送效率不如之间cpp版本的nodejs-client

**Comment by JanYork** [comment]
> > 现在新版本的nodejs，哥们有没有测试过消息发送速率，我测试700条每秒，发送效率不如之间cpp版本的nodejs-client
> 
> 现在新版本的nodejs，哥们有没有测试过消息发送速率，我测试700条每秒，发送效率不如之间cpp版本的nodejs-client

This phenomenon should be normal, before it is based on node.js cpp extension implementation, the execution rate of the cpp language is relatively better than node.js, while the cpp extension situation should be out of the node.js event loop.
Right now it's based on grpc-js, sending messages is single threaded, and the messages occur in the event loop of node.js.

I just have a feeling that this is possible.
